pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "rajatrokde/frontend-login"
        DOCKER_TAG = "latest"
        KUBE_CONFIG = credentials('kubeconfig')
    }

    stages {

        stage('Checkout Code') {
            steps {
                git 'https://github.com/rajatrokde/YOUR-REPO.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE:$DOCKER_TAG .'
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh 'echo $PASS | docker login -u $USER --password-stdin'
                }
            }
        }

        stage('Push Image') {
            steps {
                sh 'docker push $DOCKER_IMAGE:$DOCKER_TAG'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh '''
                export KUBECONFIG=$KUBE_CONFIG
                kubectl set image deployment/frontend frontend=$DOCKER_IMAGE:$DOCKER_TAG
                kubectl rollout status deployment/frontend
                '''
            }
        }
    }

    post {
        success {
            echo "✅ Deployment Successful"
        }
        failure {
            echo "❌ Deployment Failed"
        }
    }
}
