apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1 # Number of replicas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
<<<<<<< HEAD
        - name: youtube-clone
          image: rajatrokde/youtube-clone:v1
=======
        - name: nginx
          image: nginx
>>>>>>> parent of d7ebf6e (Update pod.yml)
          ports:
            - containerPort: 80
