apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  selector:
    app: nginx  # Must match the labels in the Deployment
  ports:
    - protocol: TCP
      port: 80   # Service port
      targetPort: 80  # Container port
  type: NodePort  # Can be changed to LoadBalancer or NodePort for external access
