apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: raj
  name: raj
spec:
  containers:
  - image: rajatrokde/php-backend
    name: raj
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
